### ISSUE TITLE
Case Insensitive

### ISSUE THREAD

**Issue by geoffjukes** [iky/nameko-slack#3]
Great addition to Nameko, thanks for releasing it!

Is there a way to toggle the case sensitivity for the `handle_message` regex?

Python regexes are case-sensitive by default, which can be frustrating when sending commands from a Slack mobile client (which automatically capitalizes the first word)

Geoff

**Comment by iky** [comment]
Hi @geoffjukes, thanks.)

You can switch flags directly in regular expression patterns. See `(?aiLmsux)` in 
[Python re documentation](https://docs.python.org/3/library/re.html#regular-expression-syntax)

You can place group with `?i` at the beginning of your pattern to switch to case-insensitive matching:

```python
    @handle_message('(?i)^spam')
    def handle_spam(self, event, message):
        ''' handle any message starting with ``spam`` ignoring letters case
        '''
```

In addition to the the "in-line" switch, adding a flag argument to ``handle_message`` for setting flags by passing them to ``re.compile`` seems like a nice enhancement of the API (something like ``@handle_message('^spam', re_flags=re.IGNORECASE)``).

**Comment by geoffjukes** [comment]
Thanks!

I did not know I could make it insensitive inline (I must have missed it in the docs) so thanks for the pointer!

Geoff
